# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'SwiftObjcFramework', :subspecs => ['Swift', 'ObjC'], :path => '../'
  # pod 'SwiftObjcFramework', :path => '../'
  # pod 'SwiftObjcFramework/ObjC', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    case target.name
    when 'SwiftObjcFramework'
      pre_compiled_header = installer.pods_project.files
       .find { |file| file.display_name == "SwiftObjcFramework-prefix.pch" }
      break if target.headers_build_phase.include? pre_compiled_header
      build_file = target.headers_build_phase.add_file_reference pre_compiled_header
      build_file.settings = { 'ATTRIBUTES' => ['Public'] }
    end
  end
end
